/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 01-May-2020 8:01:49 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */

DROP TABLE IF EXISTS `Courses` CASCADE
;

DROP TABLE IF EXISTS `LearnRequirements` CASCADE
;

DROP TABLE IF EXISTS `Lectures` CASCADE
;

DROP TABLE IF EXISTS `PDF` CASCADE
;

DROP TABLE IF EXISTS `Schedule` CASCADE
;

DROP TABLE IF EXISTS `Sections` CASCADE
;

DROP TABLE IF EXISTS `Users` CASCADE
;

DROP TABLE IF EXISTS `UsersCourses` CASCADE
;

/* Create Tables */

CREATE TABLE `Courses`
(
	`idCourse` INT NOT NULL AUTO_INCREMENT,
	`courseSubtitle` VARCHAR(50) NULL,
	`courseTitle` VARCHAR(50) NULL,
	`courseDescription` TEXT NULL,
	`languaje` VARCHAR(50) NULL,
	`level` VARCHAR(50) NULL,
	`topic` VARCHAR(50) NULL,
	`module` VARCHAR(50) NULL,
	`primarylyTaught` VARCHAR(50) NULL,
	`imageCourse` VARCHAR(50) NULL,
	`videoPromotional` VARCHAR(50) NULL,
	`price` VARCHAR(50) NULL,
	`welcomeMessage` VARCHAR(50) NULL,
	`congratulationsMessage` VARCHAR(50) NULL,
	`idUsers` INT NULL,
	CONSTRAINT `PK_Courses` PRIMARY KEY (`idCourse` ASC)
)

;

CREATE TABLE `LearnRequirements`
(
	`idCourse` INT NOT NULL,
	`idRequirementLearn` INT NOT NULL AUTO_INCREMENT,
	`text` VARCHAR(700) NULL,
	`requirementLearn` VARCHAR(700) NULL,
	CONSTRAINT `PK_LearnRequirements` PRIMARY KEY (`idRequirementLearn` ASC, `idCourse` ASC)
)

;

CREATE TABLE `Lectures`
(
	`idLecture` INT NOT NULL AUTO_INCREMENT,
	`nameLecture` VARCHAR(100) NULL,
	`duracion` VARCHAR(50) NULL,
	`idSection` INT NULL,
	`video` VARCHAR(700) NULL,
	CONSTRAINT `PK_Lectures` PRIMARY KEY (`idLecture` ASC)
)

;

CREATE TABLE `PDF`
(
	`idPDF` INT NOT NULL AUTO_INCREMENT,
	`idLecture` INT NOT NULL,
	`namePDF` VARCHAR(50) NULL,
	`linkPDF` TEXT NULL,
	CONSTRAINT `PK_PDF` PRIMARY KEY (`idPDF` ASC, `idLecture` ASC)
)

;

CREATE TABLE `Schedule`
(
	`idCourse` INT NOT NULL,
	`idSchedule` INT NOT NULL AUTO_INCREMENT,
	`day` VARCHAR(15) NULL,
	`startTime` TIME NULL,
	`finishTime` TIME NULL,
	CONSTRAINT `PK_Schedule_Course` PRIMARY KEY (`idCourse` ASC, `idSchedule` ASC)
)

;

CREATE TABLE `Sections`
(
	`idSection` INT NOT NULL AUTO_INCREMENT,
	`nameSection` VARCHAR(100) NULL,
	`idCourse` INT NOT NULL,
	CONSTRAINT `PK_Section` PRIMARY KEY (`idSection` ASC)
)

;

CREATE TABLE `Users`
(
	`idUsers` INT NOT NULL AUTO_INCREMENT,
	`firstName` VARCHAR(20) NOT NULL,
	`lastName` VARCHAR(20) NULL,
	`email` TEXT NOT NULL,
	`phoneNumber` VARCHAR(20) NULL,
	`education` VARCHAR(50) NULL,
	`userType` VARCHAR(50) NOT NULL,
	`password` TEXT NOT NULL,
	`question1` VARCHAR(100) NULL,
	`question2` VARCHAR(100) NULL,
	`question3` VARCHAR(100) NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`idUsers` ASC)
)

;

CREATE TABLE `UsersCourses`
(
	`idUsers` INT NOT NULL AUTO_INCREMENT,
	`idCourse` INT NOT NULL,
	`wishList` INT NULL,
	`cart` INT NULL,
	`subscribe` INT NULL,
	`courseProgress` FLOAT(10,2) NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`idUsers` ASC, `idCourse` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Courses`
 ADD INDEX `IXFK_Courses_Users` (`idUsers` ASC)
;

ALTER TABLE `LearnRequirements`
 ADD INDEX `IXFK_LearnRequirements_Courses` (`idCourse` ASC)
;

ALTER TABLE `Lectures`
 ADD INDEX `IXFK_Lectures_Sections` (`idSection` ASC)
;

ALTER TABLE `PDF`
 ADD INDEX `IXFK_PDF_Lectures` (`idLecture` ASC)
;

ALTER TABLE `Schedule`
 ADD INDEX `IXFK_Schedule_Courses` (`idCourse` ASC)
;

ALTER TABLE `Sections`
 ADD INDEX `IXFK_Sections_Courses` (`idCourse` ASC)
;

ALTER TABLE `UsersCourses`
 ADD INDEX `IXFK_Users_Courses` (`idCourse` ASC)
;

ALTER TABLE `UsersCourses`
 ADD INDEX `IXFK_Users_Users` (`idUsers` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Courses`
 ADD CONSTRAINT `FK_Courses_Users`
	FOREIGN KEY (`idUsers`) REFERENCES `Users` (`idUsers`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `LearnRequirements`
 ADD CONSTRAINT `FK_LearnRequirements_Courses`
	FOREIGN KEY (`idCourse`) REFERENCES `Courses` (`idCourse`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Lectures`
 ADD CONSTRAINT `FK_Lectures_Sections`
	FOREIGN KEY (`idSection`) REFERENCES `Sections` (`idSection`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `PDF`
 ADD CONSTRAINT `FK_PDF_Lectures`
	FOREIGN KEY (`idLecture`) REFERENCES `Lectures` (`idLecture`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Schedule`
 ADD CONSTRAINT `FK_Schedule_Courses`
	FOREIGN KEY (`idCourse`) REFERENCES `Courses` (`idCourse`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Sections`
 ADD CONSTRAINT `FK_Sections_Courses`
	FOREIGN KEY (`idCourse`) REFERENCES  () ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `UsersCourses`
 ADD CONSTRAINT `FK_Users_Courses`
	FOREIGN KEY (`idCourse`) REFERENCES `Courses` (`idCourse`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `UsersCourses`
 ADD CONSTRAINT `FK_Users_Users`
	FOREIGN KEY (`idUsers`) REFERENCES `Users` (`idUsers`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;
